//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnualCostProjection
    {
        public System.Guid Id { get; set; }
        public System.Guid CountryProgrammeId { get; set; }
        public System.Guid MasterBudgetCategoryId { get; set; }
        public decimal AmountProjected { get; set; }
        public Nullable<System.Guid> CurrencyId { get; set; }
    
        public virtual CountryProgramme CountryProgramme { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual MasterBudgetCategory MasterBudgetCategory { get; set; }
    }
}
