//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Approver
    {
        public Approver()
        {
            this.Notifications = new HashSet<Notification>();
        }
    
        public System.Guid Id { get; set; }
        public string ActivityCode { get; set; }
        public System.Guid UserId { get; set; }
        public string ActionType { get; set; }
        public int Priority { get; set; }
        public System.Guid AssistantId { get; set; }
        public System.Guid CountryProgrammeId { get; set; }
        public Nullable<System.Guid> FinanceLimitId { get; set; }
        public Nullable<System.Guid> ProjectDonorId { get; set; }
    
        public virtual CountryProgramme CountryProgramme { get; set; }
        public virtual FinanceLimit FinanceLimit { get; set; }
        public virtual ProjectDonor ProjectDonor { get; set; }
        public virtual SystemUser SystemUser { get; set; }
        public virtual SystemUser SystemUser1 { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
