//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetManagment
    {
        public System.Guid Id { get; set; }
        public System.Guid AssetId { get; set; }
        public string ManagementAction { get; set; }
        public string PartnerName { get; set; }
        public Nullable<System.Guid> currentProjectId { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.Guid ActionTakenBy { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual ProjectDonor ProjectDonor { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
