//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public Asset()
        {
            this.AssetLogs = new HashSet<AssetLog>();
            this.AssetManagments = new HashSet<AssetManagment>();
            this.Depreciations = new HashSet<Depreciation>();
            this.FleetDetails = new HashSet<FleetDetail>();
            this.WarehouseReleaseItems = new HashSet<WarehouseReleaseItem>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string SerialNumber { get; set; }
        public string AssetNumber { get; set; }
        public Nullable<int> Lifespan { get; set; }
        public decimal SalvageValue { get; set; }
        public Nullable<int> DepreciationPeriods { get; set; }
        public Nullable<System.Guid> CurrentOwnerId { get; set; }
        public Nullable<System.Guid> CurrentProjectDonorId { get; set; }
        public Nullable<System.Guid> CurrentSubOfficeId { get; set; }
        public Nullable<System.Guid> CurrentWareHouseId { get; set; }
        public Nullable<System.Guid> GoodsReceivedNoteItemId { get; set; }
        public bool IsReleased { get; set; }
        public long Weight { get; set; }
        public Nullable<bool> IsAssigned { get; set; }
        public string DepreciationType { get; set; }
        public byte[] Image { get; set; }
        public Nullable<double> OpeningAccDepreciaiton { get; set; }
        public Nullable<double> PercentageDepr { get; set; }
        public bool UseLifeSpan { get; set; }
        public System.Guid CountryProgramId { get; set; }
        public Nullable<System.Guid> ItemId { get; set; }
        public Nullable<double> PurchaseValue { get; set; }
        public long Index { get; set; }
        public System.Guid DepreciationCurrencyId { get; set; }
        public bool IsFleet { get; set; }
        public System.DateTime AcquisionDate { get; set; }
        public Nullable<System.Guid> OriginalProjectId { get; set; }
        public string ActionType { get; set; }
        public bool IsDesposed { get; set; }
        public bool IsAssetStateChanged { get; set; }
    
        public virtual CountrySubOffice CountrySubOffice { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual GoodsReceivedNoteItem GoodsReceivedNoteItem { get; set; }
        public virtual Item Item { get; set; }
        public virtual ProjectDonor ProjectDonor { get; set; }
        public virtual ProjectDonor ProjectDonor1 { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual WareHouse WareHouse { get; set; }
        public virtual ICollection<AssetLog> AssetLogs { get; set; }
        public virtual ICollection<AssetManagment> AssetManagments { get; set; }
        public virtual ICollection<Depreciation> Depreciations { get; set; }
        public virtual ICollection<FleetDetail> FleetDetails { get; set; }
        public virtual ICollection<WarehouseReleaseItem> WarehouseReleaseItems { get; set; }
    }
}
