//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetLog
    {
        public long Id { get; set; }
        public System.Guid AssetId { get; set; }
        public string Name { get; set; }
        public string SerialNumber { get; set; }
        public string Number { get; set; }
        public string Type { get; set; }
        public string Model { get; set; }
        public Nullable<int> Lifespan { get; set; }
        public Nullable<decimal> SalvageValue { get; set; }
        public Nullable<decimal> NetBookValue { get; set; }
        public Nullable<decimal> DepreciationMonthly { get; set; }
        public Nullable<int> DepreciationMonths { get; set; }
        public Nullable<System.Guid> CurrentOwnerId { get; set; }
        public Nullable<System.Guid> CurrentProjectId { get; set; }
        public Nullable<System.Guid> CurrentSubOfficeId { get; set; }
        public Nullable<System.Guid> CurrentWareHouseId { get; set; }
    
        public virtual Asset Asset { get; set; }
    }
}
