//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttachedDocument
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> DocumentId { get; set; }
        public string Name { get; set; }
        public string RefNo { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public string DocumentType { get; set; }
        public Nullable<long> FileSize { get; set; }
        public byte[] FileContent { get; set; }
        public Nullable<System.Guid> CountryProgrammeId { get; set; }
        public Nullable<System.DateTime> AttachedOn { get; set; }
        public Nullable<System.Guid> AttachedBy { get; set; }
        public string ContentType { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
