//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bin
    {
        public Bin()
        {
            this.BinItems = new HashSet<BinItem>();
        }
    
        public System.Guid Id { get; set; }
        public string RefNumber { get; set; }
        public Nullable<long> QTY { get; set; }
        public string Description { get; set; }
        public string WHDemarcation { get; set; }
        public Nullable<System.Guid> OrderRequestItemId { get; set; }
        public System.Guid PackageId { get; set; }
        public System.Guid WareHouseId { get; set; }
        public System.Guid CountryProgrammeId { get; set; }
        public System.Guid PreparedBy { get; set; }
        public System.DateTime PreparedOn { get; set; }
        public Nullable<System.Guid> ProcurementPlanItemId { get; set; }
    
        public virtual ICollection<BinItem> BinItems { get; set; }
        public virtual ItemPackage ItemPackage { get; set; }
        public virtual OrderRequestItem OrderRequestItem { get; set; }
        public virtual ProcurementPlanItem ProcurementPlanItem { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual WareHouse WareHouse { get; set; }
    }
}
