//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinItem
    {
        public System.Guid Id { get; set; }
        public System.Guid BinId { get; set; }
        public Nullable<System.Guid> GoodsReceivedNoteItemId { get; set; }
        public Nullable<System.Guid> WarehouseReleaseItemId { get; set; }
        public long QTYReceived { get; set; }
        public long QTYIssued { get; set; }
        public long BalanceStock { get; set; }
        public Nullable<System.DateTime> ExpirelyDate { get; set; }
        public string Remarks { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.Guid WHManagerId { get; set; }
    
        public virtual Bin Bin { get; set; }
        public virtual GoodsReceivedNoteItem GoodsReceivedNoteItem { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual WarehouseReleaseItem WarehouseReleaseItem { get; set; }
    }
}
