//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckListCategory
    {
        public CheckListCategory()
        {
            this.ServiceCheckLists = new HashSet<ServiceCheckList>();
        }
    
        public System.Guid Id { get; set; }
        public double Name { get; set; }
        public string Description { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.Guid CountryprogrammeId { get; set; }
    
        public virtual ICollection<ServiceCheckList> ServiceCheckLists { get; set; }
    }
}
