//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompletionCertificate
    {
        public System.Guid Id { get; set; }
        public string RefNumber { get; set; }
        public string Purpose { get; set; }
        public string ProjectTitle { get; set; }
        public string Location { get; set; }
        public string WorksService { get; set; }
        public System.Guid PurchaseOrderId { get; set; }
        public System.Guid OfficeId { get; set; }
        public System.Guid DRCOfficeId { get; set; }
        public System.Guid ConfirmedBy { get; set; }
        public string Remarks { get; set; }
        public bool IsSubmitted { get; set; }
        public bool IsApproved { get; set; }
        public bool IsRejected { get; set; }
        public System.Guid CountryProgrammeId { get; set; }
        public System.Guid PreparedBy { get; set; }
        public Nullable<System.Guid> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public System.DateTime PreparedOn { get; set; }
    
        public virtual CountrySubOffice CountrySubOffice { get; set; }
        public virtual CountrySubOffice CountrySubOffice1 { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
        public virtual Staff Staff2 { get; set; }
    }
}
