//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryProgramme
    {
        public CountryProgramme()
        {
            this.AccountCodes = new HashSet<AccountCode>();
            this.AnnualCostProjections = new HashSet<AnnualCostProjection>();
            this.Approvers = new HashSet<Approver>();
            this.CountrySubOffices = new HashSet<CountrySubOffice>();
            this.CountrySubProgrammes = new HashSet<CountrySubProgramme>();
            this.Donors = new HashSet<Donor>();
            this.FinanceLimits = new HashSet<FinanceLimit>();
            this.ItemClassifications = new HashSet<ItemClassification>();
            this.MasterBudgetCategories = new HashSet<MasterBudgetCategory>();
            this.OrderRequests = new HashSet<OrderRequest>();
            this.Projects = new HashSet<Project>();
            this.TenderingTypes = new HashSet<TenderingType>();
            this.WarehouseReleases = new HashSet<WarehouseRelease>();
            this.WayBills = new HashSet<WayBill>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid CountryId { get; set; }
        public string Address { get; set; }
        public string PrimaryPhone { get; set; }
        public string SecondaryPhone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string WebAddress { get; set; }
        public string ProgrammeName { get; set; }
        public Nullable<System.Guid> MBCurrencyId { get; set; }
        public string ShortName { get; set; }
        public string AdministratorEmail { get; set; }
        public byte[] Logo { get; set; }
    
        public virtual ICollection<AccountCode> AccountCodes { get; set; }
        public virtual ICollection<AnnualCostProjection> AnnualCostProjections { get; set; }
        public virtual ICollection<Approver> Approvers { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<CountrySubOffice> CountrySubOffices { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual ICollection<CountrySubProgramme> CountrySubProgrammes { get; set; }
        public virtual ICollection<Donor> Donors { get; set; }
        public virtual ICollection<FinanceLimit> FinanceLimits { get; set; }
        public virtual ICollection<ItemClassification> ItemClassifications { get; set; }
        public virtual ICollection<MasterBudgetCategory> MasterBudgetCategories { get; set; }
        public virtual ICollection<OrderRequest> OrderRequests { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<TenderingType> TenderingTypes { get; set; }
        public virtual ICollection<WarehouseRelease> WarehouseReleases { get; set; }
        public virtual ICollection<WayBill> WayBills { get; set; }
    }
}
