//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.CountryProgrammes = new HashSet<CountryProgramme>();
            this.Donors = new HashSet<Donor>();
            this.Suppliers = new HashSet<Supplier>();
            this.Locations = new HashSet<Location>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public Nullable<System.Guid> CurrencyId { get; set; }
    
        public virtual ICollection<CountryProgramme> CountryProgrammes { get; set; }
        public virtual ICollection<Donor> Donors { get; set; }
        public virtual ICollection<Supplier> Suppliers { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
    }
}
