//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public Currency()
        {
            this.AnnualCostProjections = new HashSet<AnnualCostProjection>();
            this.Assets = new HashSet<Asset>();
            this.CountryProgrammes = new HashSet<CountryProgramme>();
            this.ExchangeRates = new HashSet<ExchangeRate>();
            this.ExchangeRates1 = new HashSet<ExchangeRate>();
            this.GarageInfoes = new HashSet<GarageInfo>();
            this.OrderRequests = new HashSet<OrderRequest>();
            this.OrderRequests1 = new HashSet<OrderRequest>();
            this.PaymentRequests = new HashSet<PaymentRequest>();
            this.PaymentRequests1 = new HashSet<PaymentRequest>();
            this.ProcurementPlanItems = new HashSet<ProcurementPlanItem>();
            this.ProjectDonors = new HashSet<ProjectDonor>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.PurchaseOrders1 = new HashSet<PurchaseOrder>();
            this.TenderingTypes = new HashSet<TenderingType>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Symbol { get; set; }
        public System.Guid CountryProgrammeId { get; set; }
    
        public virtual ICollection<AnnualCostProjection> AnnualCostProjections { get; set; }
        public virtual ICollection<Asset> Assets { get; set; }
        public virtual ICollection<CountryProgramme> CountryProgrammes { get; set; }
        public virtual ICollection<ExchangeRate> ExchangeRates { get; set; }
        public virtual ICollection<ExchangeRate> ExchangeRates1 { get; set; }
        public virtual ICollection<GarageInfo> GarageInfoes { get; set; }
        public virtual ICollection<OrderRequest> OrderRequests { get; set; }
        public virtual ICollection<OrderRequest> OrderRequests1 { get; set; }
        public virtual ICollection<PaymentRequest> PaymentRequests { get; set; }
        public virtual ICollection<PaymentRequest> PaymentRequests1 { get; set; }
        public virtual ICollection<ProcurementPlanItem> ProcurementPlanItems { get; set; }
        public virtual ICollection<ProjectDonor> ProjectDonors { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders1 { get; set; }
        public virtual ICollection<TenderingType> TenderingTypes { get; set; }
    }
}
