//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.PaymentDossierDocuments = new HashSet<PaymentDossierDocument>();
            this.PurchaseOrderDocuments = new HashSet<PurchaseOrderDocument>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<PaymentDossierDocument> PaymentDossierDocuments { get; set; }
        public virtual ICollection<PurchaseOrderDocument> PurchaseOrderDocuments { get; set; }
    }
}
