//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentBackDating
    {
        public System.Guid Id { get; set; }
        public System.DateTime PreviousDate { get; set; }
        public System.DateTime NewDate { get; set; }
        public Nullable<System.Guid> OrderRequestId { get; set; }
        public Nullable<System.Guid> PurchaseOrderId { get; set; }
        public System.Guid BackDatedBy { get; set; }
        public System.DateTime BackDatedOn { get; set; }
        public string Reason { get; set; }
    
        public virtual OrderRequest OrderRequest { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
