//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentAudit
    {
        public System.Guid Id { get; set; }
        public System.Guid DocumentId { get; set; }
        public string DocumentType { get; set; }
        public Nullable<System.Guid> PreparedBy { get; set; }
        public Nullable<System.Guid> ReviewedBy { get; set; }
        public Nullable<System.Guid> AuthorizedBy { get; set; }
        public Nullable<System.Guid> VerifiedBy { get; set; }
        public Nullable<System.Guid> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public Nullable<System.DateTime> PreparedOn { get; set; }
        public Nullable<System.DateTime> ReviewedOn { get; set; }
        public Nullable<System.DateTime> AuthorizedOn { get; set; }
        public Nullable<System.DateTime> IsAprovedOn { get; set; }
        public Nullable<bool> IsSubmitted { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsReviewed { get; set; }
        public Nullable<bool> IsAuthorized { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public System.Guid CountryProgrammeId { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
    }
}
