//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentPreparer
    {
        public System.Guid Id { get; set; }
        public string DocumentCode { get; set; }
        public System.Guid PreparerId { get; set; }
        public System.Guid ProjectDonorId { get; set; }
    
        public virtual ProjectDonor ProjectDonor { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
