//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment2Fleet
    {
        public System.Guid Id { get; set; }
        public System.Guid FleetId { get; set; }
        public System.Guid EquipmentId { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual FleetDetail FleetDetail { get; set; }
        public virtual FleetEquipment FleetEquipment { get; set; }
    }
}
