//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeRate
    {
        public System.Guid Id { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public System.Guid MainCurrencyId { get; set; }
        public System.Guid LocalCurrencyId { get; set; }
        public Nullable<double> Rate { get; set; }
        public System.Guid CountryProgrammeId { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
    }
}
