//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FleetMajorIncidence
    {
        public FleetMajorIncidence()
        {
            this.FleetDailyManagements = new HashSet<FleetDailyManagement>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.Guid CountryProgramId { get; set; }
    
        public virtual ICollection<FleetDailyManagement> FleetDailyManagements { get; set; }
    }
}
