//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FleetDetail
    {
        public FleetDetail()
        {
            this.Equipment2Fleet = new HashSet<Equipment2Fleet>();
            this.FleetDailyManagements = new HashSet<FleetDailyManagement>();
            this.GarageInfoes = new HashSet<GarageInfo>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid AssetId { get; set; }
        public Nullable<System.Guid> ModelId { get; set; }
        public string ModelYear { get; set; }
        public string PlateNo { get; set; }
        public string EngineNo { get; set; }
        public string ChassisNo { get; set; }
        public Nullable<System.Guid> InsuranceTypeId { get; set; }
        public Nullable<System.DateTime> InsuranceExpiryDate { get; set; }
        public string InitialMilleage { get; set; }
        public string FuelType { get; set; }
        public string FleetType { get; set; }
        public Nullable<System.Guid> CountryProgrammeId { get; set; }
        public Nullable<System.Guid> DutyTypeId { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<System.Guid> DriverInfoId { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual DutyType DutyType { get; set; }
        public virtual ICollection<Equipment2Fleet> Equipment2Fleet { get; set; }
        public virtual ICollection<FleetDailyManagement> FleetDailyManagements { get; set; }
        public virtual InsuranceType InsuranceType { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual VehicleModel VehicleModel { get; set; }
        public virtual ICollection<GarageInfo> GarageInfoes { get; set; }
    }
}
