//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GarageSeviceCheck
    {
        public System.Guid Id { get; set; }
        public System.Guid GarageInfoId { get; set; }
        public System.Guid ServiceCheckId { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.Guid ServiceId { get; set; }
    
        public virtual GarageInfo GarageInfo { get; set; }
        public virtual ServiceCheckList ServiceCheckList { get; set; }
    }
}
