//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GarageInfo
    {
        public GarageInfo()
        {
            this.GarageSeviceChecks = new HashSet<GarageSeviceCheck>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> FleetId { get; set; }
        public Nullable<System.DateTime> Dateken { get; set; }
        public string ReasonType { get; set; }
        public Nullable<double> IfServiceCurrentMilleage { get; set; }
        public Nullable<double> IfServiceNextMilleage { get; set; }
        public string OtherProblemsDescription { get; set; }
        public Nullable<System.Guid> CurrencyId { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<System.DateTime> DateOutOfGarage { get; set; }
        public System.Guid SupplierId { get; set; }
        public Nullable<double> MilleageOut { get; set; }
        public System.DateTime IssueDate { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual FleetDetail FleetDetail { get; set; }
        public virtual ICollection<GarageSeviceCheck> GarageSeviceChecks { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
