//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenralInventory
    {
        public string AssetName { get; set; }
        public string AssetSerialNo { get; set; }
        public string AssetNumber { get; set; }
        public Nullable<int> Lifespan { get; set; }
        public decimal SalvageValue { get; set; }
        public Nullable<int> DepreciationPeriods { get; set; }
        public bool IsReleased { get; set; }
        public long Weight { get; set; }
        public Nullable<bool> IsAssigned { get; set; }
        public string DepreciationType { get; set; }
        public Nullable<double> PercentageDepr { get; set; }
        public bool UseLifeSpan { get; set; }
        public Nullable<double> PurchaseValue { get; set; }
        public bool IsFleet { get; set; }
        public System.DateTime AcquisionDate { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public string ItemSerialNo { get; set; }
        public string CurrencyName { get; set; }
        public string CurrencyShortName { get; set; }
        public string CategoryCode { get; set; }
        public string CategoryName { get; set; }
        public string ItemClassication { get; set; }
        public string ClassificationDescription { get; set; }
        public string UnitOfMeasure { get; set; }
        public string ProjectNumber { get; set; }
        public string ProjectShortName { get; set; }
        public string ProjectName { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string DonorShortName { get; set; }
        public string DonorName { get; set; }
        public string StaffName { get; set; }
        public string Designation { get; set; }
        public string Warehouse { get; set; }
        public string Locatioin { get; set; }
        public System.Guid CountryProgramId { get; set; }
        public System.Guid AssetId { get; set; }
        public Nullable<System.Guid> StaffId { get; set; }
        public System.Guid ProjectDonorId { get; set; }
        public System.Guid WareHouseId { get; set; }
        public System.Guid UnitOfMeasureId { get; set; }
        public System.Guid ItemCategoryId { get; set; }
        public System.Guid ClassicationId { get; set; }
        public System.Guid ProjectId { get; set; }
        public System.Guid DonorId { get; set; }
        public System.Guid LocationId { get; set; }
        public Nullable<System.Guid> DesignationId { get; set; }
        public Nullable<System.Guid> PersonId { get; set; }
        public System.Guid CurrencyId { get; set; }
    }
}
