//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsReceivedNoteItem
    {
        public GoodsReceivedNoteItem()
        {
            this.Assets = new HashSet<Asset>();
            this.BinItems = new HashSet<BinItem>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid GoodsReceivedNoteId { get; set; }
        public System.Guid PurchaseOrderItemId { get; set; }
        public decimal QuantityDelivered { get; set; }
        public decimal QuantityDamaged { get; set; }
        public string Comments { get; set; }
        public bool IsInventory { get; set; }
    
        public virtual ICollection<Asset> Assets { get; set; }
        public virtual ICollection<BinItem> BinItems { get; set; }
        public virtual GoodsReceivedNote GoodsReceivedNote { get; set; }
        public virtual PurchaseOrderItem PurchaseOrderItem { get; set; }
    }
}
