//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsIssuedVoucher
    {
        public GoodsIssuedVoucher()
        {
            this.GoodsIssuedVoucherItems = new HashSet<GoodsIssuedVoucherItem>();
        }
    
        public System.Guid Id { get; set; }
        public string RefNumber { get; set; }
        public string TransporterVehiclePlateNo { get; set; }
        public string Consignee { get; set; }
        public string WaybillNo { get; set; }
        public System.Guid WareHouseReleaseId { get; set; }
        public System.Guid CountryProgrammeId { get; set; }
        public System.Guid PreparedBy { get; set; }
        public System.Guid Receivedby { get; set; }
        public System.DateTime PreparedOn { get; set; }
        public bool IsSubmitted { get; set; }
    
        public virtual ICollection<GoodsIssuedVoucherItem> GoodsIssuedVoucherItems { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
        public virtual WarehouseRelease WarehouseRelease { get; set; }
    }
}
