//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public Inventory()
        {
            this.WarehouseReleaseItems = new HashSet<WarehouseReleaseItem>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ItemId { get; set; }
        public long Quantity { get; set; }
        public System.Guid CountryProgrammeId { get; set; }
        public System.Guid WareHouseId { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual WareHouse WareHouse { get; set; }
        public virtual ICollection<WarehouseReleaseItem> WarehouseReleaseItems { get; set; }
    }
}
