//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryQTY
    {
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public string SerialNumber { get; set; }
        public string CategoryCode { get; set; }
        public string CategoryName { get; set; }
        public string ClasificationName { get; set; }
        public string UnitCode { get; set; }
        public string UnitDescription { get; set; }
    }
}
