//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Assets = new HashSet<Asset>();
            this.Inventories = new HashSet<Inventory>();
            this.ItemPackages = new HashSet<ItemPackage>();
            this.OrderRequestItems = new HashSet<OrderRequestItem>();
            this.ProcurementPlanItems = new HashSet<ProcurementPlanItem>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ItemCategoryId { get; set; }
        public System.Guid ItemClassificationId { get; set; }
        public System.Guid UnitOfMessureId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string SerialNumber { get; set; }
        public System.Guid CountryProgrammeId { get; set; }
        public Nullable<System.Guid> ModelId { get; set; }
        public Nullable<System.Guid> TypeId { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual ICollection<Asset> Assets { get; set; }
        public virtual ICollection<Inventory> Inventories { get; set; }
        public virtual ItemCategory ItemCategory { get; set; }
        public virtual ItemClassification ItemClassification { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        public virtual ICollection<ItemPackage> ItemPackages { get; set; }
        public virtual ItemModel ItemModel { get; set; }
        public virtual ICollection<OrderRequestItem> OrderRequestItems { get; set; }
        public virtual ICollection<ProcurementPlanItem> ProcurementPlanItems { get; set; }
        public virtual ItemType ItemType { get; set; }
    }
}
