//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.CountrySubOffices = new HashSet<CountrySubOffice>();
            this.OrderRequests = new HashSet<OrderRequest>();
            this.OrderRequests1 = new HashSet<OrderRequest>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.WareHouses = new HashSet<WareHouse>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Description { get; set; }
        public System.Guid CountryId { get; set; }
        public System.Guid CountryProgrammeId { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<CountrySubOffice> CountrySubOffices { get; set; }
        public virtual ICollection<OrderRequest> OrderRequests { get; set; }
        public virtual ICollection<OrderRequest> OrderRequests1 { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<WareHouse> WareHouses { get; set; }
    }
}
