//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterBudgetCategory
    {
        public MasterBudgetCategory()
        {
            this.AnnualCostProjections = new HashSet<AnnualCostProjection>();
            this.GeneralLedgers = new HashSet<GeneralLedger>();
        }
    
        public System.Guid Id { get; set; }
        public string Number { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> CountryProgrammeId { get; set; }
    
        public virtual ICollection<AnnualCostProjection> AnnualCostProjections { get; set; }
        public virtual CountryProgramme CountryProgramme { get; set; }
        public virtual ICollection<GeneralLedger> GeneralLedgers { get; set; }
    }
}
