//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderRequestItem
    {
        public OrderRequestItem()
        {
            this.Bins = new HashSet<Bin>();
            this.BudgetCommitments = new HashSet<BudgetCommitment>();
            this.PurchaseOrderItems = new HashSet<PurchaseOrderItem>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid OrderRequestId { get; set; }
        public System.Guid ItemId { get; set; }
        public string ItemDescription { get; set; }
        public decimal Quantity { get; set; }
        public decimal EstimatedUnitPrice { get; set; }
        public decimal EstimatedPrice { get; set; }
        public System.Guid BudgetLineId { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.Guid> ProcurementPlanItemId { get; set; }
    
        public virtual ICollection<Bin> Bins { get; set; }
        public virtual ICollection<BudgetCommitment> BudgetCommitments { get; set; }
        public virtual Item Item { get; set; }
        public virtual OrderRequest OrderRequest { get; set; }
        public virtual ProcurementPlanItem ProcurementPlanItem { get; set; }
        public virtual ProjectBudget ProjectBudget { get; set; }
        public virtual ICollection<PurchaseOrderItem> PurchaseOrderItems { get; set; }
    }
}
