//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentVoucherBudgetLine
    {
        public System.Guid Id { get; set; }
        public System.Guid PaymentVoucherId { get; set; }
        public System.Guid PaymentRequestItemId { get; set; }
        public string Description { get; set; }
        public Nullable<double> Amount { get; set; }
        public System.Guid GeneralLedgerId { get; set; }
    
        public virtual GeneralLedger GeneralLedger { get; set; }
        public virtual PaymentRequestBudgetLine PaymentRequestBudgetLine { get; set; }
        public virtual PaymentVoucher PaymentVoucher { get; set; }
    }
}
