//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDossierDocument
    {
        public System.Guid Id { get; set; }
        public System.Guid DocumentId { get; set; }
        public string RefNumber { get; set; }
        public Nullable<System.Guid> PaymentRequestId { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual PaymentRequest PaymentRequest { get; set; }
    }
}
