//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentVoucher
    {
        public PaymentVoucher()
        {
            this.PaymentVoucherBudgetLines = new HashSet<PaymentVoucherBudgetLine>();
        }
    
        public System.Guid Id { get; set; }
        public string RefNumber { get; set; }
        public System.Guid PaymentRequestId { get; set; }
        public string ProjectBankAccount { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public System.Guid PreparedBy { get; set; }
        public Nullable<System.Guid> AuthorizedBy { get; set; }
        public Nullable<bool> IsAuthorized { get; set; }
        public Nullable<System.DateTime> PreparedOn { get; set; }
        public Nullable<System.DateTime> AuthorizedOn { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public System.Guid CountryProgrammeId { get; set; }
        public Nullable<bool> IsSubmitted { get; set; }
    
        public virtual PaymentRequest PaymentRequest { get; set; }
        public virtual ICollection<PaymentVoucherBudgetLine> PaymentVoucherBudgetLines { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
    }
}
