//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Staffs = new HashSet<Staff>();
        }
    
        public System.Guid Id { get; set; }
        public string FirstName { get; set; }
        public string OtherNames { get; set; }
        public string PhotoLocation { get; set; }
        public byte[] SignatureImage { get; set; }
        public string OfficialEmail { get; set; }
        public string OfficialPhone { get; set; }
        public string IDNo { get; set; }
        public System.Guid CountryProgrammeId { get; set; }
    
        public virtual ICollection<Staff> Staffs { get; set; }
    }
}
