//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcurementPlan
    {
        public ProcurementPlan()
        {
            this.Notifications = new HashSet<Notification>();
            this.ProcurementPlanItems = new HashSet<ProcurementPlanItem>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ProjectDonorId { get; set; }
        public System.Guid PreparingOfficeId { get; set; }
        public System.Guid PreparedBy { get; set; }
        public System.DateTime PreparedOn { get; set; }
        public string RefNumber { get; set; }
        public bool IsApproved1 { get; set; }
        public bool IsApproved2 { get; set; }
        public bool IsReviewed { get; set; }
        public bool IsAuthorized { get; set; }
        public Nullable<System.Guid> ApprovedBy1 { get; set; }
        public Nullable<System.Guid> ReviewedBy { get; set; }
        public Nullable<System.Guid> ApprovedBy2 { get; set; }
        public Nullable<System.Guid> AuthorizedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn1 { get; set; }
        public Nullable<System.DateTime> ApprovedOn2 { get; set; }
        public Nullable<System.DateTime> ReviewedOn { get; set; }
        public Nullable<System.DateTime> AuthorizedOn { get; set; }
        public bool IsSubmitted { get; set; }
        public bool IsRejected { get; set; }
        public string Approval1RejectMessage { get; set; }
        public string Approval2RejectMessage { get; set; }
        public string ReviewRejectMessage { get; set; }
        public string AuthorizationRejectMessage { get; set; }
    
        public virtual CountrySubOffice CountrySubOffice { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
        public virtual Staff Staff2 { get; set; }
        public virtual ProjectDonor ProjectDonor { get; set; }
        public virtual Staff Staff3 { get; set; }
        public virtual Staff Staff4 { get; set; }
        public virtual ICollection<ProcurementPlanItem> ProcurementPlanItems { get; set; }
    }
}
