//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcurementPlanItem
    {
        public ProcurementPlanItem()
        {
            this.Bins = new HashSet<Bin>();
            this.OrderRequestItems = new HashSet<OrderRequestItem>();
            this.PurchaseOrderItems = new HashSet<PurchaseOrderItem>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ProcurementPlanId { get; set; }
        public System.Guid ItemId { get; set; }
        public string ItemDescription { get; set; }
        public int Quantity { get; set; }
        public decimal UnitCost { get; set; }
        public decimal TotalCost { get; set; }
        public System.Guid CurrencyId { get; set; }
        public System.Guid BudgetLineId { get; set; }
        public bool AddedToOR { get; set; }
        public bool IsApproved { get; set; }
        public bool IsRemoved { get; set; }
        public Nullable<int> DeliveredAmount { get; set; }
        public Nullable<double> ApproximateCBM { get; set; }
        public Nullable<int> WarehouseSpaceRequired { get; set; }
        public bool IsApproved2 { get; set; }
        public bool IsReviewed { get; set; }
        public bool IsAuthorized { get; set; }
    
        public virtual ICollection<Bin> Bins { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Item Item { get; set; }
        public virtual ICollection<OrderRequestItem> OrderRequestItems { get; set; }
        public virtual ProcurementPlan ProcurementPlan { get; set; }
        public virtual ProjectBudget ProjectBudget { get; set; }
        public virtual ICollection<PurchaseOrderItem> PurchaseOrderItems { get; set; }
    }
}
