//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectBudget
    {
        public ProjectBudget()
        {
            this.BudgetCommitments = new HashSet<BudgetCommitment>();
            this.OrderRequestItems = new HashSet<OrderRequestItem>();
            this.PaymentRequestBudgetLines = new HashSet<PaymentRequestBudgetLine>();
            this.ProcurementPlanItems = new HashSet<ProcurementPlanItem>();
            this.PurchaseOrderItems = new HashSet<PurchaseOrderItem>();
            this.Rebookings = new HashSet<Rebooking>();
            this.Rebookings1 = new HashSet<Rebooking>();
        }
    
        public System.Guid Id { get; set; }
        public string LineNumber { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> BudgetCategoryId { get; set; }
        public decimal TotalBudget { get; set; }
        public Nullable<decimal> TotalCommitted { get; set; }
        public Nullable<decimal> TotalPosted { get; set; }
        public Nullable<decimal> RemainingBalance { get; set; }
        public Nullable<System.Guid> GeneralLedgerId { get; set; }
        public Nullable<double> OverrunAdjustment { get; set; }
    
        public virtual BudgetCategory BudgetCategory { get; set; }
        public virtual ICollection<BudgetCommitment> BudgetCommitments { get; set; }
        public virtual GeneralLedger GeneralLedger { get; set; }
        public virtual ICollection<OrderRequestItem> OrderRequestItems { get; set; }
        public virtual ICollection<PaymentRequestBudgetLine> PaymentRequestBudgetLines { get; set; }
        public virtual ICollection<ProcurementPlanItem> ProcurementPlanItems { get; set; }
        public virtual ICollection<PurchaseOrderItem> PurchaseOrderItems { get; set; }
        public virtual ICollection<Rebooking> Rebookings { get; set; }
        public virtual ICollection<Rebooking> Rebookings1 { get; set; }
    }
}
