//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.ProjectDonors = new HashSet<ProjectDonor>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string ProjectNumber { get; set; }
        public System.Guid CountryProgrammeId { get; set; }
    
        public virtual CountryProgramme CountryProgramme { get; set; }
        public virtual ICollection<ProjectDonor> ProjectDonors { get; set; }
    }
}
