//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public PurchaseOrder()
        {
            this.CompletionCertificates = new HashSet<CompletionCertificate>();
            this.DocumentBackDatings = new HashSet<DocumentBackDating>();
            this.Notifications = new HashSet<Notification>();
            this.PaymentRequests = new HashSet<PaymentRequest>();
            this.PurchaseOrderItems = new HashSet<PurchaseOrderItem>();
        }
    
        public System.Guid Id { get; set; }
        public string RefNumber { get; set; }
        public Nullable<System.Guid> OrderRequestId { get; set; }
        public Nullable<System.Guid> PaymentTermId { get; set; }
        public System.Guid SupplierId { get; set; }
        public Nullable<System.Guid> ShippingTermId { get; set; }
        public System.Guid DeliveryAddress { get; set; }
        public Nullable<bool> FromOneBL { get; set; }
        public string Remarks { get; set; }
        public System.Guid PreparedBy { get; set; }
        public System.Guid CurrencyId { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string ShippingMarks { get; set; }
        public string ConsigneeAddress { get; set; }
        public string ConsigneeEmail1 { get; set; }
        public string ConsigneeEmail2 { get; set; }
        public Nullable<System.Guid> CountryProgrammeId { get; set; }
        public string RejectedReviewRemarks { get; set; }
        public string RejectedAuthorizeRemarks { get; set; }
        public Nullable<System.DateTime> PreparedOn { get; set; }
        public long RecordCount { get; set; }
        public string QuotationRef { get; set; }
        public Nullable<System.Guid> MBCurrencyId { get; set; }
        public Nullable<decimal> MBValue { get; set; }
        public string AdditionalRemarks { get; set; }
        public bool IsSubmitted { get; set; }
        public bool IsRejected { get; set; }
        public Nullable<System.Guid> ProjectDonorId { get; set; }
        public System.DateTime PODate { get; set; }
        public System.DateTime LatestDeliveryDate { get; set; }
        public string OtherSpecify { get; set; }
        public Nullable<double> PFGPercentage { get; set; }
        public bool ProformaRequired { get; set; }
        public bool CommercialInvoiceRequired { get; set; }
        public bool WayBillRequired { get; set; }
        public bool PackingListRequired { get; set; }
        public bool DeliveryNoteRequired { get; set; }
        public bool ManualsRequired { get; set; }
        public bool CertificatesReqired { get; set; }
        public bool OtherRequired { get; set; }
        public bool PrefinancingGuaranteeRequired { get; set; }
        public Nullable<System.Guid> ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public bool IsInternational { get; set; }
        public Nullable<System.Guid> TenderingTypeId { get; set; }
        public string TenderNumber { get; set; }
        public Nullable<bool> WaiverAcquired { get; set; }
    
        public virtual ICollection<CompletionCertificate> CompletionCertificates { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
        public virtual ICollection<DocumentBackDating> DocumentBackDatings { get; set; }
        public virtual Location Location { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual OrderRequest OrderRequest { get; set; }
        public virtual ICollection<PaymentRequest> PaymentRequests { get; set; }
        public virtual PaymentTerm PaymentTerm { get; set; }
        public virtual ProjectDonor ProjectDonor { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
        public virtual ShippingTerm ShippingTerm { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual TenderingType TenderingType { get; set; }
        public virtual ICollection<PurchaseOrderItem> PurchaseOrderItems { get; set; }
    }
}
