//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderItem
    {
        public PurchaseOrderItem()
        {
            this.BudgetCommitments = new HashSet<BudgetCommitment>();
            this.GoodsReceivedNoteItems = new HashSet<GoodsReceivedNoteItem>();
            this.PaymentRequestBudgetLines = new HashSet<PaymentRequestBudgetLine>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid PurchaseOrderId { get; set; }
        public Nullable<System.Guid> OrderRequestItemId { get; set; }
        public Nullable<System.Guid> ProcurementPlanItemId { get; set; }
        public int Quantity { get; set; }
        public double UnitPrice { get; set; }
        public decimal TotalPrice { get; set; }
        public Nullable<System.Guid> BudgetLineId { get; set; }
        public string Remarks { get; set; }
    
        public virtual ICollection<BudgetCommitment> BudgetCommitments { get; set; }
        public virtual ICollection<GoodsReceivedNoteItem> GoodsReceivedNoteItems { get; set; }
        public virtual OrderRequestItem OrderRequestItem { get; set; }
        public virtual ICollection<PaymentRequestBudgetLine> PaymentRequestBudgetLines { get; set; }
        public virtual ProcurementPlanItem ProcurementPlanItem { get; set; }
        public virtual ProjectBudget ProjectBudget { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
