//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rebooking
    {
        public System.Guid Id { get; set; }
        public System.Guid FromBudgetLineId { get; set; }
        public System.Guid ToBudgetLineId { get; set; }
        public decimal FromAmount { get; set; }
        public decimal ToAmount { get; set; }
        public bool IsFullRebook { get; set; }
        public System.Guid RebookedBy { get; set; }
        public System.DateTime RebookedOn { get; set; }
        public Nullable<System.Guid> BudgetPostingId { get; set; }
        public Nullable<System.Guid> BudgetCommitmentId { get; set; }
    
        public virtual BudgetCommitment BudgetCommitment { get; set; }
        public virtual BudgetPosting BudgetPosting { get; set; }
        public virtual ProjectBudget ProjectBudget { get; set; }
        public virtual ProjectBudget ProjectBudget1 { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
