//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCheckList
    {
        public ServiceCheckList()
        {
            this.GarageSeviceChecks = new HashSet<GarageSeviceCheck>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ServiceCategoryId { get; set; }
        public string Name { get; set; }
        public string Discription { get; set; }
    
        public virtual CheckListCategory CheckListCategory { get; set; }
        public virtual ICollection<GarageSeviceCheck> GarageSeviceChecks { get; set; }
    }
}
