//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public Staff()
        {
            this.Assets = new HashSet<Asset>();
            this.AssetManagments = new HashSet<AssetManagment>();
            this.AttachedDocuments = new HashSet<AttachedDocument>();
            this.Bins = new HashSet<Bin>();
            this.BinItems = new HashSet<BinItem>();
            this.BudgetPostings = new HashSet<BudgetPosting>();
            this.CompletionCertificates = new HashSet<CompletionCertificate>();
            this.CompletionCertificates1 = new HashSet<CompletionCertificate>();
            this.CompletionCertificates2 = new HashSet<CompletionCertificate>();
            this.DocumentBackDatings = new HashSet<DocumentBackDating>();
            this.DocumentPreparers = new HashSet<DocumentPreparer>();
            this.FleetDailyManagements = new HashSet<FleetDailyManagement>();
            this.FleetDetails = new HashSet<FleetDetail>();
            this.GoodsIssuedVouchers = new HashSet<GoodsIssuedVoucher>();
            this.GoodsIssuedVouchers1 = new HashSet<GoodsIssuedVoucher>();
            this.GoodsReceivedNotes = new HashSet<GoodsReceivedNote>();
            this.GoodsReceivedNotes1 = new HashSet<GoodsReceivedNote>();
            this.OrderRequests = new HashSet<OrderRequest>();
            this.OrderRequests1 = new HashSet<OrderRequest>();
            this.OrderRequests2 = new HashSet<OrderRequest>();
            this.OrderRequests3 = new HashSet<OrderRequest>();
            this.PaymentRequests = new HashSet<PaymentRequest>();
            this.PaymentRequests1 = new HashSet<PaymentRequest>();
            this.PaymentRequests2 = new HashSet<PaymentRequest>();
            this.PaymentRequests3 = new HashSet<PaymentRequest>();
            this.PaymentVouchers = new HashSet<PaymentVoucher>();
            this.PaymentVouchers1 = new HashSet<PaymentVoucher>();
            this.ProcurementPlans = new HashSet<ProcurementPlan>();
            this.ProcurementPlans1 = new HashSet<ProcurementPlan>();
            this.ProcurementPlans2 = new HashSet<ProcurementPlan>();
            this.ProcurementPlans3 = new HashSet<ProcurementPlan>();
            this.ProcurementPlans4 = new HashSet<ProcurementPlan>();
            this.ProjectDonors = new HashSet<ProjectDonor>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.PurchaseOrders1 = new HashSet<PurchaseOrder>();
            this.Rebookings = new HashSet<Rebooking>();
            this.SystemUsers = new HashSet<SystemUser>();
            this.WarehouseReleases = new HashSet<WarehouseRelease>();
            this.WarehouseReleases1 = new HashSet<WarehouseRelease>();
            this.WarehouseReleases2 = new HashSet<WarehouseRelease>();
            this.WayBills = new HashSet<WayBill>();
            this.WayBills1 = new HashSet<WayBill>();
            this.WayBills2 = new HashSet<WayBill>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid PersonId { get; set; }
        public System.Guid DesignationId { get; set; }
        public Nullable<System.Guid> CountrySubOfficeId { get; set; }
        public Nullable<System.Guid> FinanceLimitId { get; set; }
    
        public virtual ICollection<Asset> Assets { get; set; }
        public virtual ICollection<AssetManagment> AssetManagments { get; set; }
        public virtual ICollection<AttachedDocument> AttachedDocuments { get; set; }
        public virtual ICollection<Bin> Bins { get; set; }
        public virtual ICollection<BinItem> BinItems { get; set; }
        public virtual ICollection<BudgetPosting> BudgetPostings { get; set; }
        public virtual ICollection<CompletionCertificate> CompletionCertificates { get; set; }
        public virtual ICollection<CompletionCertificate> CompletionCertificates1 { get; set; }
        public virtual ICollection<CompletionCertificate> CompletionCertificates2 { get; set; }
        public virtual CountrySubOffice CountrySubOffice { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual ICollection<DocumentBackDating> DocumentBackDatings { get; set; }
        public virtual ICollection<DocumentPreparer> DocumentPreparers { get; set; }
        public virtual FinanceLimit FinanceLimit { get; set; }
        public virtual ICollection<FleetDailyManagement> FleetDailyManagements { get; set; }
        public virtual ICollection<FleetDetail> FleetDetails { get; set; }
        public virtual ICollection<GoodsIssuedVoucher> GoodsIssuedVouchers { get; set; }
        public virtual ICollection<GoodsIssuedVoucher> GoodsIssuedVouchers1 { get; set; }
        public virtual ICollection<GoodsReceivedNote> GoodsReceivedNotes { get; set; }
        public virtual ICollection<GoodsReceivedNote> GoodsReceivedNotes1 { get; set; }
        public virtual ICollection<OrderRequest> OrderRequests { get; set; }
        public virtual ICollection<OrderRequest> OrderRequests1 { get; set; }
        public virtual ICollection<OrderRequest> OrderRequests2 { get; set; }
        public virtual ICollection<OrderRequest> OrderRequests3 { get; set; }
        public virtual ICollection<PaymentRequest> PaymentRequests { get; set; }
        public virtual ICollection<PaymentRequest> PaymentRequests1 { get; set; }
        public virtual ICollection<PaymentRequest> PaymentRequests2 { get; set; }
        public virtual ICollection<PaymentRequest> PaymentRequests3 { get; set; }
        public virtual ICollection<PaymentVoucher> PaymentVouchers { get; set; }
        public virtual ICollection<PaymentVoucher> PaymentVouchers1 { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<ProcurementPlan> ProcurementPlans { get; set; }
        public virtual ICollection<ProcurementPlan> ProcurementPlans1 { get; set; }
        public virtual ICollection<ProcurementPlan> ProcurementPlans2 { get; set; }
        public virtual ICollection<ProcurementPlan> ProcurementPlans3 { get; set; }
        public virtual ICollection<ProcurementPlan> ProcurementPlans4 { get; set; }
        public virtual ICollection<ProjectDonor> ProjectDonors { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders1 { get; set; }
        public virtual ICollection<Rebooking> Rebookings { get; set; }
        public virtual ICollection<SystemUser> SystemUsers { get; set; }
        public virtual ICollection<WarehouseRelease> WarehouseReleases { get; set; }
        public virtual ICollection<WarehouseRelease> WarehouseReleases1 { get; set; }
        public virtual ICollection<WarehouseRelease> WarehouseReleases2 { get; set; }
        public virtual ICollection<WayBill> WayBills { get; set; }
        public virtual ICollection<WayBill> WayBills1 { get; set; }
        public virtual ICollection<WayBill> WayBills2 { get; set; }
    }
}
