//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        public SystemUser()
        {
            this.Approvers = new HashSet<Approver>();
            this.Approvers1 = new HashSet<Approver>();
            this.SystemUserRoles = new HashSet<SystemUserRole>();
        }
    
        public System.Guid Id { get; set; }
        public string Password { get; set; }
        public Nullable<System.Guid> StaffId { get; set; }
        public string PIN { get; set; }
        public string PasswordSalt { get; set; }
        public bool Active { get; set; }
        public bool Locked { get; set; }
        public string LastIpAddress { get; set; }
        public int UserLoginCount { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public bool IsAvailable { get; set; }
        public Nullable<System.Guid> PasswordResetCode { get; set; }
        public Nullable<System.DateTime> GenerationTime { get; set; }
    
        public virtual ICollection<Approver> Approvers { get; set; }
        public virtual ICollection<Approver> Approvers1 { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual ICollection<SystemUserRole> SystemUserRoles { get; set; }
    }
}
