//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemRolePrivilege
    {
        public System.Guid UserRoleId { get; set; }
        public System.Guid PrivilegeId { get; set; }
    
        public virtual SystemPrivilege SystemPrivilege { get; set; }
    }
}
