//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_BudgetPipeline
    {
        public Nullable<System.Guid> ProjectDonorId { get; set; }
        public string CategoryName { get; set; }
        public string CategoryNumber { get; set; }
        public string BudgetLine { get; set; }
        public string BLDescription { get; set; }
        public Nullable<decimal> RFPPost { get; set; }
        public Nullable<System.DateTime> RFPPostDate { get; set; }
        public System.Guid BudgetLineId { get; set; }
    }
}
