//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_BudgetPipeLineReport
    {
        public string CategoryName { get; set; }
        public string CategoryNumber { get; set; }
        public string BudgetLine { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> TotalBudget { get; set; }
        public string ProjectNo { get; set; }
        public Nullable<System.Guid> ProjectId { get; set; }
        public Nullable<System.Guid> CountryProgrammeId { get; set; }
        public string ProjectPeriod { get; set; }
        public Nullable<int> ProjectDuration { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> PostedFunds { get; set; }
        public string PostDate { get; set; }
        public Nullable<System.DateTime> PostFundDate { get; set; }
        public Nullable<int> PostDateNo { get; set; }
    }
}
