//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DocumentStatus
    {
        public System.Guid DocumentId { get; set; }
        public string DocumentType { get; set; }
        public string preparedBy { get; set; }
        public string DocPreparedBy { get; set; }
        public string DocReviewedBy { get; set; }
        public string ReviewedBy { get; set; }
        public string AuthorizedBy { get; set; }
        public string DocAuthorizedBy { get; set; }
        public string VerifiedBy { get; set; }
        public string DocVerifiedBy { get; set; }
        public string ApprovedBy { get; set; }
        public string DocApprovedBy { get; set; }
        public Nullable<System.DateTime> PreparedOn { get; set; }
        public Nullable<System.DateTime> ReviewedOn { get; set; }
        public Nullable<System.DateTime> AuthorizedOn { get; set; }
        public Nullable<bool> IsSubmitted { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsReviewed { get; set; }
        public Nullable<bool> IsAuthorized { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public System.Guid CountryProgrammeId { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string DocNo { get; set; }
        public string ProjectNo { get; set; }
        public Nullable<decimal> DocValue { get; set; }
        public string DocStatus { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
    }
}
