//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VBudgetDetail
    {
        public string ProjectName { get; set; }
        public string ProjectShortName { get; set; }
        public string BugdetCategory { get; set; }
        public string BugdetCategoryNo { get; set; }
        public string BugdetLine { get; set; }
        public string LineNumber { get; set; }
        public System.Guid BugdetLineID { get; set; }
        public System.Guid CategoryID { get; set; }
        public string ProjectNumber { get; set; }
        public System.Guid ProjectID { get; set; }
        public decimal TotalBudget { get; set; }
        public Nullable<decimal> TotalCommitted { get; set; }
        public Nullable<decimal> TotalPosted { get; set; }
        public Nullable<decimal> RemainingBalance { get; set; }
        public System.Guid DonorId { get; set; }
        public string DonorName { get; set; }
        public string DonorShortName { get; set; }
    }
}
