//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VStaffDetail
    {
        public System.Guid StaffID { get; set; }
        public string StaffName { get; set; }
        public string PhotoLocation { get; set; }
        public byte[] SignatureImage { get; set; }
        public string OfficialEmail { get; set; }
        public string OfficialPhone { get; set; }
        public string IDNo { get; set; }
        public string Designation { get; set; }
        public string ShortName { get; set; }
        public string Description { get; set; }
        public System.Guid DesignationID { get; set; }
        public System.Guid PersonID { get; set; }
        public string SubOfficeName { get; set; }
        public System.Guid CountryProgrammeId { get; set; }
    }
}
