//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseRelease
    {
        public WarehouseRelease()
        {
            this.GoodsIssuedVouchers = new HashSet<GoodsIssuedVoucher>();
            this.Notifications = new HashSet<Notification>();
            this.WarehouseReleaseItems = new HashSet<WarehouseReleaseItem>();
            this.WayBills = new HashSet<WayBill>();
        }
    
        public System.Guid Id { get; set; }
        public string RefNumber { get; set; }
        public System.Guid PreparedBy { get; set; }
        public Nullable<System.Guid> ApprovedBy { get; set; }
        public Nullable<bool> GoodCondition { get; set; }
        public Nullable<bool> CorrectQuantity { get; set; }
        public bool NotReleased { get; set; }
        public Nullable<System.Guid> ReceivedBy { get; set; }
        public string ReceivingUnit { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public Nullable<System.Guid> ReleasedBy { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public System.Guid CountryProgrammeId { get; set; }
        public System.DateTime PreparedOn { get; set; }
        public long RecordCount { get; set; }
        public bool IsSubmitted { get; set; }
        public System.DateTime RequestDate { get; set; }
        public bool IsRejected { get; set; }
        public string RejectedWRFComments { get; set; }
        public bool IsApproved { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public Nullable<System.DateTime> RejectedOn { get; set; }
        public System.Guid WareHouseId { get; set; }
    
        public virtual CountryProgramme CountryProgramme { get; set; }
        public virtual ICollection<GoodsIssuedVoucher> GoodsIssuedVouchers { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
        public virtual Staff Staff2 { get; set; }
        public virtual WareHouse WareHouse { get; set; }
        public virtual WareHouse WareHouse1 { get; set; }
        public virtual ICollection<WarehouseReleaseItem> WarehouseReleaseItems { get; set; }
        public virtual ICollection<WayBill> WayBills { get; set; }
    }
}
