//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseReleaseItem
    {
        public WarehouseReleaseItem()
        {
            this.BinItems = new HashSet<BinItem>();
            this.GoodsIssuedVoucherItems = new HashSet<GoodsIssuedVoucherItem>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid WarehouseReleaseId { get; set; }
        public System.Guid InventoryId { get; set; }
        public Nullable<System.Guid> AssetId { get; set; }
        public decimal Quantity { get; set; }
        public string Comments { get; set; }
        public Nullable<long> QuantityReceived { get; set; }
        public Nullable<long> QuantityDamaged { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual ICollection<BinItem> BinItems { get; set; }
        public virtual ICollection<GoodsIssuedVoucherItem> GoodsIssuedVoucherItems { get; set; }
        public virtual Inventory Inventory { get; set; }
        public virtual WarehouseRelease WarehouseRelease { get; set; }
    }
}
