//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareHouse
    {
        public WareHouse()
        {
            this.Assets = new HashSet<Asset>();
            this.Bins = new HashSet<Bin>();
            this.GoodsReceivedNotes = new HashSet<GoodsReceivedNote>();
            this.Inventories = new HashSet<Inventory>();
            this.WarehouseReleases = new HashSet<WarehouseRelease>();
            this.WarehouseReleases1 = new HashSet<WarehouseRelease>();
            this.WayBills = new HashSet<WayBill>();
            this.WayBills1 = new HashSet<WayBill>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> LocationId { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> SubOfficeId { get; set; }
        public System.Guid CountryProgrammeId { get; set; }
    
        public virtual ICollection<Asset> Assets { get; set; }
        public virtual ICollection<Bin> Bins { get; set; }
        public virtual CountrySubOffice CountrySubOffice { get; set; }
        public virtual ICollection<GoodsReceivedNote> GoodsReceivedNotes { get; set; }
        public virtual ICollection<Inventory> Inventories { get; set; }
        public virtual Location Location { get; set; }
        public virtual ICollection<WarehouseRelease> WarehouseReleases { get; set; }
        public virtual ICollection<WarehouseRelease> WarehouseReleases1 { get; set; }
        public virtual ICollection<WayBill> WayBills { get; set; }
        public virtual ICollection<WayBill> WayBills1 { get; set; }
    }
}
